=== quetzal680/cawl/source/CAWL_1_0/CAWL_v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 sp1 (http://www.altova.com) by focusChoi (EMBRACE) -->
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Jongsun Choi (Soongsil University) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:uflow="http://www.uflow.org/CAWL1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uflow.org/CAWL1.0" elementFormDefault="qualified">
	<import namespace="http://schemas.xmlsoap.org/wsdl/" schemaLocation="http://schemas.xmlsoap.org/wsdl/"/>
	<element name="CAWL" type="uflow:uWDLType"/>
	<complexType name="documentationType">
		<sequence>
			<element name="documentation" minOccurs="0">
				<complexType mixed="true">
					<sequence>
						<any minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
	<complexType name="uWDLType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="baseOntologies">
						<complexType>
							<sequence>
								<element name="ontology" type="uflow:ontologyType" maxOccurs="unbounded"/>
							</sequence>
						</complexType>
					</element>
					<element name="serviceProviderType" type="uflow:serviceProviderTypeType" minOccurs="0" maxOccurs="unbounded"/>
					<element name="serviceProvider" type="uflow:serviceProviderType" minOccurs="0" maxOccurs="unbounded"/>
					<element name="message" type="uflow:messageType" minOccurs="0" maxOccurs="unbounded"/>
					<element name="variable" type="uflow:variableType" minOccurs="0" maxOccurs="unbounded"/>
					<element name="activator" type="uflow:activatorType" minOccurs="0" maxOccurs="unbounded"/>
					<element name="flow" type="uflow:flowType" maxOccurs="unbounded"/>
				</sequence>
				<attribute name="name" type="NCName"/>
				<attribute name="targetNamespace" type="anyURI"/>
				<attribute name="version" type="string"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="ontologyType">
		<complexContent>
			<extension base="uflow:documentationType">
				<attribute name="location" type="anyURI" use="required"/>
				<attribute name="namespace" type="anyURI" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="serviceProviderTypeType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="portType" type="uflow:portTypeType" minOccurs="0" maxOccurs="unbounded"/>
				</sequence>
				<attribute name="name" type="NCName" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="serviceProviderType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="locator" type="uflow:locatorType"/>
				</sequence>
				<attribute name="name" type="NCName" use="required"/>
				<attribute name="type" type="QName" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="locatorType">
		<sequence>
			<any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="type">
			<simpleType>
				<restriction base="string">
					<enumeration value="static"/>
					<enumeration value="UDDI"/>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="service" type="QName"/>
	</complexType>
	<complexType name="portTypeType">
		<complexContent>
			<extension base="wsdl:tPortType">
				<sequence>
					<element name="import" minOccurs="0" maxOccurs="unbounded">
						<complexType>
							<attribute name="portType" type="QName"/>
							<attribute name="operation" type="NCName"/>
						</complexType>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="messageType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="part" type="uflow:partType" minOccurs="0" maxOccurs="unbounded"/>
				</sequence>
				<attribute name="name" type="NCName" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="partType">
		<complexContent>
			<extension base="uflow:documentationType">
				<attribute name="name" type="NCName" use="required"/>
				<attribute name="element" type="QName" use="optional"/>
				<attribute name="type" type="QName" use="optional"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="variableType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="initialize" type="uflow:initializeType" minOccurs="0" maxOccurs="unbounded"/>
				</sequence>
				<attribute name="name" type="NCName" use="required"/>
				<attribute name="type" type="QName" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="initializeType">
		<sequence>
			<element name="from" type="uflow:fromType"/>
		</sequence>
		<attribute name="part" type="NCName" use="required"/>
	</complexType>
	<complexType name="fromType">
		<attribute name="variable" type="QName" use="optional"/>
		<attribute name="part" type="NCName" use="optional"/>
		<attribute name="expression" type="xsd:string" use="optional"/>
	</complexType>
	<complexType name="activatorType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="condition" type="uflow:conditionType"/>
					<element name="activate" type="uflow:activateType" minOccurs="0" maxOccurs="unbounded"/>
					<element name="deactivate" type="uflow:deactivateType" minOccurs="0" maxOccurs="unbounded"/>
				</sequence>
				<attribute name="name" type="xsd:string" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="conditionType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="case" type="uflow:caseType" minOccurs="0" maxOccurs="unbounded"/>
					<element name="context" minOccurs="0">
						<complexType>
							<complexContent>
								<extension base="uflow:contextType">
									<attribute name="priority" type="string" use="optional"/>
								</extension>
							</complexContent>
						</complexType>
					</element>
				</sequence>
				<attribute name="expression" type="xsd:string" use="optional"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="caseType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="event" type="uflow:eventType" minOccurs="0"/>
				</sequence>
				<attribute name="name" type="NCName" use="optional"/>
				<attribute name="expression" type="xsd:string" use="optional"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="eventType">
		<complexContent>
			<extension base="uflow:documentationType">
				<attribute name="serviceProvider" type="QName" use="required"/>
				<attribute name="portType" type="NCName" use="required"/>
				<attribute name="operation" type="NCName" use="required"/>
				<attribute name="output" type="QName" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="contextType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="rule" maxOccurs="unbounded">
						<complexType>
							<complexContent>
								<extension base="uflow:ruleType">
									<attribute name="expression" type="string" use="optional"/>
								</extension>
							</complexContent>
						</complexType>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="ruleType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="constraint" maxOccurs="unbounded">
						<complexType>
							<complexContent>
								<extension base="uflow:constraintType">
									<attribute name="restriction" type="xsd:string" use="optional"/>
								</extension>
							</complexContent>
						</complexType>
					</element>
				</sequence>
				<attribute name="contribute" use="optional" default="positive">
					<annotation>
						<documentation>positive or nagative</documentation>
					</annotation>
					<simpleType>
						<restriction base="xsd:string">
							<enumeration value="positive"/>
							<enumeration value="negative"/>
						</restriction>
					</simpleType>
				</attribute>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="constraintType">
		<all>
			<element name="subject" type="uflow:subjectType"/>
			<element name="verb" type="xsd:string"/>
			<element name="object" type="uflow:objectType"/>
		</all>
		<attribute name="name" type="NCName" use="optional"/>
	</complexType>
	<complexType name="subjectType">
		<simpleContent>
			<extension base="xsd:string">
				<attribute name="type" type="string" use="optional"/>
			</extension>
		</simpleContent>
	</complexType>
	<complexType name="objectType">
		<simpleContent>
			<extension base="xsd:string">
				<attribute name="type" type="QName" use="optional"/>
			</extension>
		</simpleContent>
	</complexType>
	<complexType name="activateType">
		<complexContent>
			<extension base="uflow:documentationType">
				<attribute name="activator" type="QName" use="optional"/>
				<attribute name="flow" type="QName" use="optional"/>
				<attribute name="input" type="QName" use="optional"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="deactivateType">
		<complexContent>
			<extension base="uflow:documentationType">
				<attribute name="activator" type="QName" use="optional"/>
				<attribute name="flow" type="QName" use="optional"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="flowType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="message" type="uflow:messageType" minOccurs="0" maxOccurs="unbounded"/>
					<element name="variable" type="uflow:variableType" minOccurs="0" maxOccurs="unbounded"/>
					<element name="source">
						<complexType>
							<complexContent>
								<extension base="uflow:sourceType">
									<attribute name="name" type="string" use="optional"/>
								</extension>
							</complexContent>
						</complexType>
					</element>
					<element name="node" type="uflow:nodeType" maxOccurs="unbounded"/>
					<element name="link" type="uflow:linkType" maxOccurs="unbounded"/>
					<element name="sink" minOccurs="1">
						<complexType>
							<complexContent>
								<extension base="uflow:sinkType"/>
							</complexContent>
						</complexType>
					</element>
				</sequence>
				<attribute name="name" type="NCName" use="optional"/>
				<attribute name="default" type="xsd:boolean" use="optional"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="sourceType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="input" type="uflow:inputType" minOccurs="0"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="inputType">
		<complexContent>
			<extension base="uflow:documentationType">
				<attribute name="name" type="string" use="required"/>
				<attribute name="type" type="QName" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="nodeType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="message" type="uflow:messageType" minOccurs="0" maxOccurs="unbounded"/>
					<element name="variable" type="uflow:variableType" minOccurs="0" maxOccurs="unbounded"/>
					<element name="synchronize" minOccurs="0"/>
					<element name="condition" type="uflow:conditionType"/>
					<choice>
						<element name="invoke" minOccurs="0" maxOccurs="unbounded">
							<complexType>
								<complexContent>
									<extension base="uflow:invokeType"/>
								</complexContent>
							</complexType>
						</element>
						<element name="wait" type="uflow:waitType" minOccurs="0" maxOccurs="unbounded"/>
					</choice>
				</sequence>
				<attribute name="name" type="NCName" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="copyType">
		<sequence>
			<element name="from" type="uflow:fromType"/>
			<element name="to" type="uflow:toType"/>
		</sequence>
	</complexType>
	<complexType name="toType">
		<attribute name="variable" type="QName" use="required"/>
		<attribute name="part" type="NCName" use="optional"/>
	</complexType>
	<complexType name="invokeType">
		<attribute name="serviceProvider" type="QName" use="required"/>
		<attribute name="portType" type="NCName" use="required"/>
		<attribute name="operation" type="NCName" use="required"/>
		<attribute name="input" type="string" use="optional"/>
		<attribute name="output" type="string" use="optional"/>
		<attribute name="subflow" type="boolean" use="optional"/>
	</complexType>
	<complexType name="waitType">
		<attribute name="serviceProvider" type="QName" use="required"/>
		<attribute name="portType" type="NCName" use="required"/>
		<attribute name="operation" type="NCName" use="required"/>
		<attribute name="output" type="QName" use="optional"/>
	</complexType>
	<complexType name="linkType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="copy" type="uflow:copyType" minOccurs="0" maxOccurs="unbounded"/>
				</sequence>
				<attribute name="from" type="anyURI" use="required"/>
				<attribute name="to" type="anyURI" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="sinkType">
		<complexContent>
			<extension base="uflow:documentationType">
				<sequence>
					<element name="output" minOccurs="0">
						<complexType>
							<complexContent>
								<extension base="uflow:outputType"/>
							</complexContent>
						</complexType>
					</element>
					<element name="synchronize"/>
				</sequence>
				<attribute name="name" type="NCName"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="outputType">
		<complexContent>
			<extension base="uflow:documentationType">
				<attribute name="name" type="string" use="required"/>
				<attribute name="type" type="QName" use="required"/>
			</extension>
		</complexContent>
	</complexType>
</schema>

=== quetzal680/cawl/source/CAWL_1_0/CAWL.xml
<?xml version="1.0" encoding="UTF-8"?>
<uflow:CAWL name="MTRoomService" version="1.0.1" targetNamespace="RobotServiceTest" 
	xmlns:uflow="http://www.uflow.org/CAWL1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/root/Dropbox/workspace/uwdl/1_uWDL2_0_pre_a/CAWL_v1.0.xsd">
	<uflow:documentation>
		1. title:  Meeting Room Services using LEGO Robots
		2. Scenario_Developer: Jongsun Choi
		3. Impl_Developer: Jaehoon Jeong
		4. Modification_Date: 2010.04
	</uflow:documentation>
	<uflow:baseOntologies>
		<uflow:ontology namespace="http://ss.ssu.ac.kr/Ontology" location="http://ss.ssu.ac.kr/Ontology/CAWL"/>
	</uflow:baseOntologies>

	<uflow:serviceProvider type="Company" name="ssCom">
		<uflow:locator type="static"/>
	</uflow:serviceProvider>
	
	<uflow:message name="MTRoomService_In">
		<uflow:documentation> 
			1. Definition of messages: 알리미 서비스에 사용될 변수들의 묶음
			2. ComplexType으로 초기화함
		</uflow:documentation>
		<uflow:part type="Person" name="personName">
			<uflow:documentation>조도 서비스를 제공 받는 사람</uflow:documentation>
		</uflow:part>
		<uflow:part type="URC" name="robotName"/>
		<uflow:part type="militaryTime" name="currentTime"/>
		<uflow:part type="militaryTime" name="reservedTime"/>			
	</uflow:message>

	<uflow:message name="checkRoom">
		<uflow:part type="officeRoom" name="officeroomNum"/>
		<uflow:part type="meetingRoom" name="meetingroomNum"/>
	</uflow:message>
	
	<uflow:message name="checkRobotService">
		<uflow:part type="Check" name="checkFlow"/>
	</uflow:message>
	 
	<uflow:message name="checkDistance">
		<uflow:part type="Distance" name="R2U-Distance"/>
	</uflow:message> 
	 
	<uflow:variable type="MTRoomService_In" name="inVarUser">
		<uflow:documentation>
				1. Definition of variables: 알리미 서비스에 사용될 전역 변수
				2. 센서로부터 전송 받은 사람의 프로파일 정보를 static 하게 초기화 함
				3. inVarJohn는 personName으로부터 전달받은 내용을 저장하기 위한 변수
				4. "John"이라는 사용자 정보는 프로파일 서버를 통해 전달받아야 하는 내용, 현재는 static하게 초기화함
			</uflow:documentation>
		<uflow:initialize part="personName">
			<uflow:from expression="John"/>
		</uflow:initialize>
	</uflow:variable>
	<uflow:variable type="militaryTime" name="crtTime">
		<uflow:documentation> 현재시간은 시스템으로부터 제공받음, 00:00시로 초기화함 </uflow:documentation>
		<uflow:initialize part="currentTime">
			<uflow:from expression="0900"/>
		</uflow:initialize> 
	</uflow:variable>
	<uflow:variable type="URC" name="robot307"/>	
	<uflow:variable type="URC" name="robot313"/>					
	<uflow:variable type="returnValue" name="result">
		<uflow:documentation>subworkflow의 실행 후 결과 값 </uflow:documentation>
	</uflow:variable>						
	<uflow:variable type="robotService" name="serviceCheck">
		<uflow:documentation>워크플로우의 출력값을 위한 변수,  sink에서 사용, 1(ok)</uflow:documentation>
		<uflow:initialize part="checkFlow">
			<uflow:from expression="1"/>
		</uflow:initialize>
	</uflow:variable>
	

	<uflow:activator name="MTRoomServiceActivator">
		<uflow:condition expression="const1">
			<uflow:context>
				<uflow:rule contribute="positive">
					<uflow:constraint name="const1">
						<uflow:subject type="militaryTime">?=crtTime/currentTime</uflow:subject>
						<uflow:verb>is</uflow:verb>
						<uflow:object type="militaryTime">0900</uflow:object>
					</uflow:constraint>
				</uflow:rule>
			</uflow:context>
		</uflow:condition>
		<uflow:activate flow="MTRoomServiceFlow"/>
	</uflow:activator>
	
	
	<uflow:flow name="MTRoomServices">
		<uflow:source>
			<uflow:documentation>
				1. 워크플로우의 입력값을 정의한다.
				2. 첫번째 노드의 전이조건으로 사용할 예약시간 정보를 정으한다.
			</uflow:documentation>
			<uflow:input type="militaryTime" name="?rsvTime"/>
		</uflow:source>

		<uflow:node name="TeaPreparation">
			<uflow:documentation> 
				1. 차(tea)를 준비하는 로봇 서비스를 호출하는 노드
				2. 전이조건: 로봇307이 307호에 있고, 현재 시간이 예약된 시간(13:40분)이다	 
			 </uflow:documentation>
			<uflow:variable type="militaryTime" name="rsvTime">
				<uflow:documentation> 
					1. 시스템은 예약시간(rsvTime)을 이전 워크플로우로부터 전달 받은 값 또는 개발자가 정한 값으로 초기화 한다.
					2. 본 시나리오에서는 개발자가 정한 값(13:40시)으로 초기화한다. </uflow:documentation>
				<uflow:initialize part="reservedTime"><uflow:from expression="13:40"/></uflow:initialize> 
			</uflow:variable>
			<uflow:condition expression="C1 and C2">
				<uflow:context>
					<uflow:rule contribute="positive">
						<uflow:constraint name="C1">
							<uflow:subject type="URC">?=Robot307/robotName</uflow:subject>
							<uflow:verb>isLocated</uflow:verb>
							<uflow:object type="officeRoom">?=roomNum/officeroomNum</uflow:object>
						</uflow:constraint>
						<uflow:constraint name="C2">
							<uflow:subject type="militaryTime">?=crtTime/currentTime</uflow:subject>
							<uflow:verb>is</uflow:verb>
							<uflow:object type="militaryTime">?=rsvTime/reservedTime</uflow:object>
						</uflow:constraint>
					</uflow:rule>
				</uflow:context>
			</uflow:condition>
			<uflow:invoke serviceProvider="ssCom" portType="TeaPreparationPT" operation="TeaRobotService" input="?rsvTime" output="?result" subflow="true"/>
		</uflow:node>

		<uflow:node name="DisplayLightInfo">
			<uflow:documentation>회의실의 조도 정보를 알려주는 서비스를 호출하는 노드</uflow:documentation>
			<uflow:variable name="roomNum" type="officeRoom">
				<uflow:documentation> 방번호는 다른 서버로부터 제공받아야 하는 정보로, 본 문서에서는  static 정보로 초기화함 </uflow:documentation>
				<uflow:initialize part="officeroomNum"><uflow:from expression="313"/></uflow:initialize>
			</uflow:variable>
			<uflow:variable type="militaryTime" name="rsvTime">
				<uflow:documentation> 
					1. 시스템은 예약시간(rsvTime)을 이전 워크플로우로부터 전달 받은 값 또는 개발자가 정한 값으로 초기화 한다.
					2. 본 시나리오에서는 개발자가 정한 값(13:50시)으로 초기화한다. </uflow:documentation>
				<uflow:initialize part="reservedTime"><uflow:from expression="13:50"/></uflow:initialize> 
			</uflow:variable>	
			<uflow:condition expression="C1 and C2 and C3">
				<uflow:context>
					<uflow:rule contribute="positive">
						<uflow:documentation>
							1. positive는 우선순위, default값이 positive
							2. C1: 현재 사용자가 해당 사무실(313호)에 있다.
							3. C2: robot313이 해당 사무실(313호)에 있다.
							3. C3: 현재 시간이 서비스를 제공하기로 예약된 시간(13:50)이다. 
						</uflow:documentation>
						<uflow:constraint name="C1">
							<uflow:subject type="Person">?=inVarUser/personName</uflow:subject>
							<uflow:verb>is</uflow:verb>
							<uflow:object type="officeRoom">?=roomNum/officeroomNum</uflow:object>
						</uflow:constraint>
						<uflow:constraint name="C2">
							<uflow:subject type="URC">?=Robot313/robotName</uflow:subject>
							<uflow:verb>isLocated</uflow:verb>
							<uflow:object type="officeRoom">?=roomNum/officeroomNum</uflow:object>
						</uflow:constraint>
						<uflow:constraint name="C3">
							<uflow:subject type="militaryTime">?=crtTime/currentTime</uflow:subject>
							<uflow:verb>is</uflow:verb>
							<uflow:object type="militaryTime">?=rsvTime/resevedTime</uflow:object>
						</uflow:constraint>
					</uflow:rule>
				</uflow:context>
			</uflow:condition>
			<uflow:invoke serviceProvider="ssCom" portType="DisplayLightInfoPT" operation="DisplayLightInfo" input="?rsvTime" output="?result" subflow="true" />
		</uflow:node>
		
		<uflow:link to="TeaPreparation" from="source"/>
		<uflow:link to="DisplayLightInfo" from="TeaPreparation"/>
		<uflow:link to="sink" from="DisplayLightInfo"/>
				
		<uflow:sink>
			<uflow:output name="?serviceCheck" type="robotService" />
			<uflow:synchronize/>
		</uflow:sink>
	</uflow:flow>
	
		
	<uflow:flow name="TeaRobotService"> <uflow:documentation> 차를 준비해주는 로봇을 이용한 서비스 </uflow:documentation>
		<uflow:variable type="militaryTime" name="rsvTime4Tea">
			<uflow:documentation>TeaRobotService에서 사용할 변수 선언 및 초기화</uflow:documentation>
			<uflow:initialize part="reservedTime"><uflow:from expression="00:00"/></uflow:initialize> 
		</uflow:variable>
		
		<uflow:source>
			<uflow:documentation>TeaPreparation 노드에서 호출할때의 예약시간(13:40)을 받음</uflow:documentation>
			<uflow:input type="militaryTime" name="?rsvTime4Tea"/>
		</uflow:source>
				
		<uflow:node name="MoveDown">
			<uflow:condition expression="C1">
				<uflow:context>
					<uflow:rule contribute="positive">
							<uflow:constraint name="C1">
							<uflow:subject type="militaryTime">?crtTime/currentTime</uflow:subject>
							<uflow:verb>is</uflow:verb>
							<uflow:object type="militaryTime">?rsvTime4Tea/reservedTime</uflow:object>
						</uflow:constraint>
					</uflow:rule>
				</uflow:context>
			</uflow:condition>
			<uflow:invoke operation="GenerationOfarmMVdown" portType="MoveDownPT" serviceProvider="ssCom" input="armMVdown:tartgetLoc" output="LEGO_CMD"/>
		</uflow:node>
					
		<uflow:node name="MoveUp">
			 <uflow:variable type="militaryTime" name="rsvTime4MVup">
				 <uflow:initialize part="reservedTime">
						<uflow:from expression="13:42"/>
					</uflow:initialize>
			 </uflow:variable>
			<uflow:condition expression="C1">
				<uflow:context>
					<uflow:rule contribute="positive">
							<uflow:constraint name="C1">
							<uflow:subject type="militaryTime">?crtTime/currentTime</uflow:subject>
							<uflow:verb>is</uflow:verb>
							<uflow:object type="militaryTime">?rsvTime4MVup/reservedTime</uflow:object>
						</uflow:constraint>
					</uflow:rule>
				</uflow:context>
			</uflow:condition>
			<uflow:invoke operation="GenerationOfarmMVdown" portType="MoveDownPT" serviceProvider="ssCom" input="armMVup:tartgetLoc" output="LEGO_CMD"/>
		</uflow:node>
			
		<uflow:link to="MoveDown" from="source"></uflow:link>
		<uflow:link to="MoveUp" from="MoveDown"></uflow:link>
		
		<uflow:sink>
			<uflow:output name="?serviceCheck" type="robotService" />
			<uflow:synchronize/>
		</uflow:sink>
	</uflow:flow>


	<uflow:flow name="DisplayLightInfo">
		<uflow:documentation> LEGO Robot1으로부터 받은 미팅룸의 발기 정보를 알려주는  서비스 </uflow:documentation>
		<uflow:variable type="officeRoom" name="roomNum">
			<uflow:initialize part="officeroomNum">
				<uflow:from expression="313"/>
			</uflow:initialize>
		</uflow:variable>
		<uflow:variable type="militaryTime" name="rsvTime4LightInfo">
			<uflow:initialize part="reservedTime">
				<uflow:from expression="00:00"/>
			</uflow:initialize>
		</uflow:variable>
